# G0.6 — Sodium 0.6.13 (single Modrinth artifact), MC 1.21.6, Java 21
minecraft_version=1.21.6
loader_version=0.16.13
fabric_version=0.127.0+1.21.6
parchmentmc_mappings=2025.06.29
java_version=21
mod_version=0.4.1-beta9-1.21.6

sodium_dep=maven.modrinth:sodium:mc1.21.6-0.6.13-fabric
iris_dep=maven.modrinth:iris:1.9.0+1.21.6-fabric
data_attachment_dep=net.fabricmc.fabric-api:fabric-rendering-data-attachment-v1:0.3.40+73761d2e3b

mc_depend=1.21.6
sodium_depend=>=0.6.0 <0.7
loader_depends=>=0.16.13
